format and cleanup

diff --git a/modules/utils/android-backup b/modules/utils/android-backup
--- a/modules/utils/android-backup
+++ b/modules/utils/android-backup
@@ -2,16 +2,16 @@
 
 print_help() {
 	#    "--------------------------------------------------------------------------------"
-    echo "android-backup"
-    echo ""
+	echo "android-backup"
+	echo ""
 	echo "backup files (mainly images and videos) from android phone"
 	echo ""
-    echo "USAGE: android-backup [OPTIONS] DEVICE"
+	echo "USAGE: android-backup [OPTIONS] DEVICE"
 	echo ""
-    echo "OPTIONS:"
-    echo "    -h, --help             print help text"
-    echo ""
-    echo "SCALE must be one of the following: 'pixel-4a', 'pixel-9pro'"
+	echo "OPTIONS:"
+	echo "    -h, --help             print help text"
+	echo ""
+	echo "SCALE must be one of the following: 'pixel-4a', 'pixel-9pro'"
 	echo ""
 	echo "The device gets mounted to /tmp/aft-mountpoint and its content gets backedup"
 	echo "in a directory inside ~/desktop/telefono-dump that depends on the specified"
@@ -33,37 +33,35 @@ exit_help() {
 }
 
 exit_error() {
-    print_help
-    echo ""
-    echo "ERROR: $1"
-    exit 1
+	print_help
+	echo ""
+	echo "ERROR: $1"
+	exit 1
 }
 
 POSITIONAL_ARGS=()
 
 while [[ $# -gt 0 ]]; do
-    case $1 in
-        -h|--help)
-            exit_help
-            ;;
-        -*)
-			exit_error "Unknown option '$1'"
-			;;
-        *)
-			POSITIONAL_ARGS+=("$1") # save positional arg
-		  	shift # past argument
-		  	;;
-    esac
+	case $1 in
+	-h | --help)
+		exit_help
+		;;
+	-*)
+		exit_error "Unknown option '$1'"
+		;;
+	*)
+		POSITIONAL_ARGS+=("$1") # save positional arg
+		shift                   # past argument
+		;;
+	esac
 done
 
 set -- "${POSITIONAL_ARGS[@]}"
 
-if [[ -z ${1+x} ]]
-then
+if [[ -z ${1+x} ]]; then
 	exit_error "No device specified"
 
-elif [[ "$1" != "pixel-4a" ]] && [[ "$1" != "pixel-9pro" ]]
-then
+elif [[ "$1" != "pixel-4a" ]] && [[ "$1" != "pixel-9pro" ]]; then
 	exit_error "Unknown device '$1'. Device must be one of the following: 'pixel-4a', 'pixel-9pro'"
 fi
 
@@ -85,20 +83,18 @@ echo ""
 echo "Mounting..."
 # Ensure mountpoint exists
 mkdir -p /tmp/aft-mountpoint
-# Mount android device to 
+# Mount android device to
 aft-mtp-mount /tmp/aft-mountpoint
 
 echo ""
 echo "Starting backup..."
-if [[ "$DEVICE" == "pixel-4a" ]]
-then
+if [[ "$DEVICE" == "pixel-4a" ]]; then
 	mkdir -p ~/desktop/telefono-dump/pixel-4a/.
 
 	# Rsync
 	rsync --info=progress2 -avzh /tmp/aft-mountpoint/Memoria\ condivisa\ interna/{DCIM,Movies,Music,Pictures,Telegram,Fran} ~/desktop/telefono-dump/pixel-4a/.
 
-elif [[ "$DEVICE" == "pixel-9pro" ]]
-then
+elif [[ "$DEVICE" == "pixel-9pro" ]]; then
 	mkdir -p ~/desktop/telefono-dump/pixel-9pro/.
 
 	# Rsync
@@ -125,6 +121,6 @@ FAIL=$(
 	echo -e "\033[1;31m  Failed to unmount! \033[0m"
 	echo "Unmount manually"
 )
-sudo -p "$SUDO_PROMPT" umount /tmp/aft-mountpoint && \
-	echo "$SUCCESS" || \
+sudo -p "$SUDO_PROMPT" umount /tmp/aft-mountpoint &&
+	echo "$SUCCESS" ||
 	echo "$FAIL"
diff --git a/modules/utils/canon-import b/modules/utils/canon-import
--- a/modules/utils/canon-import
+++ b/modules/utils/canon-import
@@ -1,31 +1,31 @@
 #!/usr/bin/env bash
 
 print_help() {
-    echo "canon-import"
-    echo ""
-    echo "automatically import images from your SD card and properly format file names,"
+	echo "canon-import"
+	echo ""
+	echo "automatically import images from your SD card and properly format file names,"
 	echo "metadata and permissions"
-    echo ""
-    echo "USAGE: canon-import [OPTIONS] DEST"
-    echo ""
-    echo "OPTIONS:"
-    #    "--- 80 characters --------------------------------------------------------------"
-    echo "    -h, --help             print help text"
+	echo ""
+	echo "USAGE: canon-import [OPTIONS] DEST"
+	echo ""
+	echo "OPTIONS:"
+	#    "--- 80 characters --------------------------------------------------------------"
+	echo "    -h, --help             print help text"
 	echo "    -s, --source=SOURCE    source of the images (default value: "
 	echo "							     /run/media/baldo/EOS_DIGITAL/DCIM/100CANON)"
 	echo "    -m, --mv               use mv instead of cp"
 	echo "    --no-img               skip images (incompatible with --no-vid)"
 	echo "    --no-vid               skip videos (incompatible with --no-img)"
 	echo "    --write-conversion     save the names conversion to a .csv file"
-    echo ""
-    echo "DEST: the destination of the images"
+	echo ""
+	echo "DEST: the destination of the images"
 }
 
 print_error() {
-    print_help
-    echo ""
-    echo "ERROR: $1"
-    exit 1
+	print_help
+	echo ""
+	echo "ERROR: $1"
+	exit 1
 }
 
 POSITIONAL_ARGS=()
@@ -36,71 +36,75 @@ NOVID=0
 WRITE_CONVERSION=0
 
 while [[ $# -gt 0 ]]; do
-    case $1 in
-        -h|--help)
-            print_help
-            exit 0
-            ;;
-        -s|--source)
-			SOURCE="$2"
-            shift # past argument
-			shift # past value
-            ;;
-		-m|--mv)
-			MV=1
-			shift
-			;;
-		--no-img)
-			NOIMG=1
-			shift
-			;;
-		--no-vid)
-			NOVID=1
-			shift
-			;;
-		--write-conversion)
-			WRITE_CONVERSION=1
-			shift
-			;;
-        -*)
-            print_error "Unknown option $1"
-            ;;
-        *)
-            POSITIONAL_ARGS+=("$1") # save positional arg
-            shift # past argument
-            ;;
-    esac
+	case $1 in
+	-h | --help)
+		print_help
+		exit 0
+		;;
+	-s | --source)
+		SOURCE="$2"
+		shift # past argument
+		shift # past value
+		;;
+	-m | --mv)
+		MV=1
+		shift
+		;;
+	--no-img)
+		NOIMG=1
+		shift
+		;;
+	--no-vid)
+		NOVID=1
+		shift
+		;;
+	--write-conversion)
+		WRITE_CONVERSION=1
+		shift
+		;;
+	-*)
+		print_error "Unknown option $1"
+		;;
+	*)
+		POSITIONAL_ARGS+=("$1") # save positional arg
+		shift                   # past argument
+		;;
+	esac
 done
 
-if [[ "$NOIMG" -eq 1 ]] && [[ "$NOVID" -eq 1 ]]
-then
+if [[ "$NOIMG" -eq 1 ]] && [[ "$NOVID" -eq 1 ]]; then
 	print_error "Cannot use both --no-img and --no-vid"
 fi
 
 set -- "${POSITIONAL_ARGS[@]}"
 
 if [[ -z ${1+x} ]]; then
-    print_error "Destination not given"
+	print_error "Destination not given"
 fi
 
 DEST="$1"
 
-# shellcheck disable=SC2207,SC2010
-if [[ "$NOIMG" -ne 1 ]] && ! ls -1 "$SOURCE" | grep -qE '^IMG_....\.(JPG|CR2)$'
-then
+function ls_match {
+	SOURCE=$1
+	REGEX=$2
+
+	for i in "$SOURCE"/*; do
+		FILENAME="$(basename "$i")"
+		if [[ $FILENAME =~ $REGEX ]]; then
+			echo "$FILENAME"
+		fi
+	done
+}
+
+mapfile -t imgs < <(ls_match "$SOURCE" '^IMG_....\.(JPG|CR2)$' | sed 's/....$//' | sort | uniq)
+if [[ "${#imgs[@]}" -eq 0 ]]; then
 	NOIMG=1
 fi
 
-# shellcheck disable=SC2207,SC2010
-if [[ "$NOVID" -ne 1 ]] && ! ls -1 "$SOURCE" | grep -qE '^MVI_....\.MP4$'
-then
+mapfile -t vids < <(ls_match "$SOURCE" '^MVI_....\.MP4$' | sed 's/....$//' | sort | uniq)
+if [[ "${#vids[@]}" -eq 0 ]]; then
 	NOVID=1
 fi
-
-# shellcheck disable=SC2207,SC2010
-[[ "$NOIMG" -ne 1 ]] && imgs=($(ls -1 "$SOURCE" | grep -E '^IMG_....\.(JPG|CR2)$' | sed 's/....$//' | sort | uniq))
-# shellcheck disable=SC2207,SC2010
-[[ "$NOVID" -ne 1 ]] && vids=($(ls -1 "$SOURCE" | grep -E '^MVI_....\.MP4$'       | sed 's/....$//'))
 
 [[ "$NOIMG" -ne 1 ]] && echo "images: ${#imgs[@]}"
 [[ "$NOVID" -ne 1 ]] && echo "videos: ${#vids[@]}"
@@ -109,27 +113,23 @@ read -rn1 -p "Procede? [y/N]: " CHOICE
 echo ""
 CHOICE="${CHOICE:-n}"
 
-if [[ "$CHOICE" != "y" ]] && [[ "$CHOICE" != "Y" ]]
-then
+if [[ "$CHOICE" != "y" ]] && [[ "$CHOICE" != "Y" ]]; then
 	echo ""
 	echo "Quitting..."
 	exit
 fi
 
-if [[ "$NOIMG" -ne 1 ]]
-then
+if [[ "$NOIMG" -ne 1 ]]; then
 	echo "Importing images..."
 
-	for i in "${!imgs[@]}"
-	do
+	for i in "${!imgs[@]}"; do
 		echo "${imgs[$i]} [$i/${#imgs[@]}]"
 
 		jpg_in="$SOURCE/${imgs[$i]}.JPG"
 		cr2_in="$SOURCE/${imgs[$i]}.CR2"
 
 		timestamp=""
-		if [[ -f "$cr2_in" ]]
-		then
+		if [[ -f "$cr2_in" ]]; then
 			timestamp=$(exiftool -s3 -DateTimeOriginal "$cr2_in" -d %Y%m%d_%H%M%S)
 		else
 			timestamp=$(exiftool -s3 -DateTimeOriginal "$jpg_in" -d %Y%m%d_%H%M%S)
@@ -137,8 +137,7 @@ then
 
 		n=0
 		# this is equivalent to a do-while, which does not exist in bash
-		while true
-		do
+		while true; do
 			jpg_out="$DEST/IMG_${timestamp}_$n.JPG"
 			cr2_out="$DEST/IMG_${timestamp}_$n.CR2"
 
@@ -147,20 +146,16 @@ then
 			n=$((n + 1))
 		done
 
-		if [[ -f "$jpg_in" ]]
-		then
-			if [[ "$MV" -eq 1 ]]
-			then
+		if [[ -f "$jpg_in" ]]; then
+			if [[ "$MV" -eq 1 ]]; then
 				mv "$jpg_in" "$jpg_out"
 			else
 				cp --preserve=timestamps "$jpg_in" "$jpg_out"
 			fi
 			chmod 644 "$jpg_out"
 		fi
-		if [[ -f "$cr2_in" ]]
-		then
-			if [[ "$MV" -eq 1 ]]
-			then
+		if [[ -f "$cr2_in" ]]; then
+			if [[ "$MV" -eq 1 ]]; then
 				mv "$cr2_in" "$cr2_out"
 			else
 				cp --preserve=timestamps "$cr2_in" "$cr2_out"
@@ -168,33 +163,30 @@ then
 			chmod 644 "$cr2_out"
 		fi
 
-		[[ $WRITE_CONVERSION -eq 1 ]] && echo "IMG_${timestamp}_$n,${imgs[$i]}" >> "$DEST/names-conversion.csv"
+		[[ $WRITE_CONVERSION -eq 1 ]] && echo "IMG_${timestamp}_$n,${imgs[$i]}" >>"$DEST/names-conversion.csv"
 	done
 
 	echo "Done importing images!"
 fi
 
-if [[ "$NOVID" -ne 1 ]]
-then
+if [[ "$NOVID" -ne 1 ]]; then
 	echo "Importing videos..."
 
-	for i in "${!vids[@]}"
-	do
+	for i in "${!vids[@]}"; do
 		echo "${vids[$i]} [$i/${#vids[@]}]"
 
 		vid_in="$SOURCE/${vids[$i]}.MP4"
 		timestamp=$(exiftool -s3 -DateTimeOriginal "$vid_in" -d %Y%m%d_%H%M%S)
 		vid_out="$DEST/MVI_$timestamp.MP4"
 
-		if [[ "$MV" -eq 1 ]]
-		then
+		if [[ "$MV" -eq 1 ]]; then
 			mv "$vid_in" "$vid_out"
 		else
 			cp --preserve=timestamps "$vid_in" "$vid_out"
 		fi
 		chmod 644 "$vid_out"
 
-		[[ $WRITE_CONVERSION -eq 1 ]] && echo "MVI_${timestamp},${vids[$i]}" >> "$DEST/names-conversion.csv"
+		[[ $WRITE_CONVERSION -eq 1 ]] && echo "MVI_${timestamp},${vids[$i]}" >>"$DEST/names-conversion.csv"
 	done
 
 	echo "Done importing videos!"
diff --git a/modules/utils/img-resize b/modules/utils/img-resize
--- a/modules/utils/img-resize
+++ b/modules/utils/img-resize
@@ -3,10 +3,10 @@
 print_help() {
     echo "img-resize"
     echo ""
-	echo "resize image(s) by a given percentage"
-	echo ""
-	echo "the resized images are put in a ./resized directory, which is created if it"
-	echo "does not exits already"
+    echo "resize image(s) by a given percentage"
+    echo ""
+    echo "the resized images are put in a ./resized directory, which is created if it"
+    echo "does not exits already"
     echo ""
     echo "USAGE: img-resize [OPTIONS] SCALE FILE [FILE ...]"
     echo ""
@@ -25,34 +25,34 @@ VERBOSE=0
 
 while [[ $# -gt 0 ]]; do
     case $1 in
-        -h|--help)
-            print_help
-            exit 0
-            ;;
-        -p|--pixel-perfect)
-            PIXEL_PERFECT=1
-            shift # past argument
-            ;;
-        -v|--verbose)
-            VERBOSE=1
-            shift # past argument
-            ;;
-        # -o|--output)
-        #     OUTPUT="$2"
-        #     shift # past argument
-        #     shift # past value
-        #     ;;
-        # -*|--*)
-        -*)
-          print_help
-          echo ""
-          echo "ERROR: Unknown option $1"
-          exit 1
-          ;;
-        *)
-          POSITIONAL_ARGS+=("$1") # save positional arg
-          shift # past argument
-          ;;
+    -h | --help)
+        print_help
+        exit 0
+        ;;
+    -p | --pixel-perfect)
+        PIXEL_PERFECT=1
+        shift # past argument
+        ;;
+    -v | --verbose)
+        VERBOSE=1
+        shift # past argument
+        ;;
+    # -o|--output)
+    #     OUTPUT="$2"
+    #     shift # past argument
+    #     shift # past value
+    #     ;;
+    # -*|--*)
+    -*)
+        print_help
+        echo ""
+        echo "ERROR: Unknown option $1"
+        exit 1
+        ;;
+    *)
+        POSITIONAL_ARGS+=("$1") # save positional arg
+        shift                   # past argument
+        ;;
     esac
 done
 
@@ -79,8 +79,7 @@ SCALE="$1"
 shift
 
 mkdir ./resized
-for i in "$@"
-do
+for i in "$@"; do
     if [[ $VERBOSE -eq 1 ]]; then
         echo "$i"
     fi
diff --git a/modules/utils/new-project b/modules/utils/new-project
--- a/modules/utils/new-project
+++ b/modules/utils/new-project
@@ -1,27 +1,27 @@
 #!/usr/bin/env bash
 
 print_help() {
-    echo "new-project"
-    echo ""
-    echo "initialize a directory for a new project with the necessary boilerplate"
-    echo ""
-    echo "USAGE: new-project [OPTIONS] TYPE"
-    echo ""
-    echo "OPTIONS:"
-    #    "--- 80 characters --------------------------------------------------------------"
-    echo "    -h, --help    print help text"
-    echo "    -g, --git     also initialize a git repository"
+	echo "new-project"
+	echo ""
+	echo "initialize a directory for a new project with the necessary boilerplate"
+	echo ""
+	echo "USAGE: new-project [OPTIONS] TYPE"
+	echo ""
+	echo "OPTIONS:"
+	#    "--- 80 characters --------------------------------------------------------------"
+	echo "    -h, --help    print help text"
+	echo "    -g, --git     also initialize a git repository"
 	echo "    -gg           initialize git repository and create initial commit (implies"
 	echo "                   -g)"
-    echo ""
-    echo "TYPE: currently supported types are 'node', 'python', 'nix-shell-application'"
+	echo ""
+	echo "TYPE: currently supported types are 'node', 'python', 'nix-shell-application'"
 }
 
 print_error() {
-    print_help
-    echo ""
-    echo "ERROR: $1"
-    exit 1
+	print_help
+	echo ""
+	echo "ERROR: $1"
+	exit 1
 }
 
 POSITIONAL_ARGS=()
@@ -29,38 +29,39 @@ GIT=0
 GGIT=0
 
 while [[ $# -gt 0 ]]; do
-    case $1 in
-        -h|--help)
-            print_help
-            exit 0
-            ;;
-        -g|--git)
-            GIT=1
-            shift # past argument
-            ;;
-		-gg)
-			GIT=1
-			GGIT=1
-			shift
-			;;
-        # -*|--*)
-        -*)
-            print_error "Unknown option $1"
-            ;;
-        *)
-            POSITIONAL_ARGS+=("$1") # save positional arg
-            shift # past argument
-            ;;
-    esac
+	case $1 in
+	-h | --help)
+		print_help
+		exit 0
+		;;
+	-g | --git)
+		GIT=1
+		shift # past argument
+		;;
+	-gg)
+		GIT=1
+		GGIT=1
+		shift
+		;;
+	# -*|--*)
+	-*)
+		print_error "Unknown option $1"
+		;;
+	*)
+		POSITIONAL_ARGS+=("$1") # save positional arg
+		shift                   # past argument
+		;;
+	esac
 done
 
 set -- "${POSITIONAL_ARGS[@]}"
 
 TYPE=$1
 
-PROJECT_NAME=$(basename "$(pwd)")
+PROJECT_NAME=$(basename "$PWD")
 
-PRETTIERRC=$(cat << EOF
+PRETTIERRC=$(
+	cat <<EOF
 {
     "printWidth": 80,
     "singleQuote": true,
@@ -74,13 +75,12 @@ PRETTIERRC=$(cat << EOF
 EOF
 )
 
-if [[ $TYPE == 'node' ]]
-then
-    [[ ! -f .prettierrc.json ]] && echo "$PRETTIERRC" > .prettierrc.json
-    [[ ! -f package.json ]] && cat <<- EOF > package.json
+if [[ $TYPE == 'node' ]]; then
+	[[ ! -f .prettierrc.json ]] && echo "$PRETTIERRC" >.prettierrc.json
+	[[ ! -f package.json ]] && cat <<-EOF >package.json
 		{
 		    "name": "$PROJECT_NAME",
-			"type": "module",
+		    "type": "module",
 		    "version": "1.0.0",
 		    "main": "index.js",
 		    "scripts": {
@@ -91,39 +91,36 @@ then
 		    "license": "ISC",
 		    "description": ""
 		}
-		EOF
-	
-	[[ ! -f index.js ]] && cat <<- EOF > index.js
-		console.log("Hello World!")
-		EOF
+	EOF
 
-    if [[ $GIT -eq 1 ]]
-    then
-        [[ ! -f .gitignore ]] && cat <<- EOF > .gitignore
+	[[ ! -f index.js ]] && cat <<-EOF >index.js
+		console.log("Hello World!")
+	EOF
+
+	if [[ $GIT -eq 1 ]]; then
+		[[ ! -f .gitignore ]] && cat <<-EOF >.gitignore
 			node_modules/
-			
+
 			.env*
 			!.env*.example
-			EOF
+		EOF
 
-		[[ ! -f README.md ]] && cat <<- EOF > README.md
+		[[ ! -f README.md ]] && cat <<-EOF >README.md
 			# $PROJECT_NAME
-			EOF
+		EOF
 
-        [[ ! -d .git ]] && { 
-            git init
-            if [[ $GGIT -eq 1 ]]
-            then
-                git add .
-                git commit -m "initial commit"
-            fi
-        }
-    fi
-elif [[ $TYPE == 'python' ]]
-then
-    [[ ! -f .prettierrc.json ]] && echo "$PRETTIERRC" > .prettierrc.json
+		[[ ! -d .git ]] && {
+			git init
+			if [[ $GGIT -eq 1 ]]; then
+				git add .
+				git commit -m "initial commit"
+			fi
+		}
+	fi
+elif [[ $TYPE == 'python' ]]; then
+	[[ ! -f .prettierrc.json ]] && echo "$PRETTIERRC" >.prettierrc.json
 
-	[[ ! -f shell.nix ]] && cat <<- EOF > shell.nix
+	[[ ! -f shell.nix ]] && cat <<-EOF >shell.nix
 		with (import <nixpkgs> {});
 		mkShell {
 		    buildInputs = [
@@ -131,38 +128,34 @@ then
 		        ]))
 		    ];
 		}
-		EOF
+	EOF
 
-    if [[ $GIT -eq 1 ]]
-    then
-        [[ ! -f .gitignore ]] && cat <<- EOF > .gitignore
+	if [[ $GIT -eq 1 ]]; then
+		[[ ! -f .gitignore ]] && cat <<-EOF >.gitignore
 			__pycache__/
 
 			.env*
 			!.env*.example
-			EOF
+		EOF
 
-
-		[[ ! -f README.md ]] && cat <<- EOF > README.md
+		[[ ! -f README.md ]] && cat <<-EOF >README.md
 			# $PROJECT_NAME
-			EOF
+		EOF
 
-        [[ ! -d .git ]] && { 
-            git init
-            if [[ $GGIT -eq 1 ]]
-            then
-                git add .
-                git commit -m "initial commit"
-            fi
-        }
-    fi
-elif [[ $TYPE == 'nix-shell-application' ]]
-then
-    [[ ! -f .prettierrc.json ]] && echo "$PRETTIERRC" > .prettierrc.json
+		[[ ! -d .git ]] && {
+			git init
+			if [[ $GGIT -eq 1 ]]; then
+				git add .
+				git commit -m "initial commit"
+			fi
+		}
+	fi
+elif [[ $TYPE == 'nix-shell-application' ]]; then
+	[[ ! -f .prettierrc.json ]] && echo "$PRETTIERRC" >.prettierrc.json
 
-	[[ ! -f source.sh ]] && cat <<- EOF > source.sh
+	[[ ! -f source.sh ]] && cat <<-EOF >source.sh
 		#!/usr/bin/env bash
-		
+
 		print_help() {
 		    #    "--------------------------------------------------------------------------------"
 		    echo "$PROJECT_NAME"
@@ -180,24 +173,24 @@ then
 		    echo ""
 		    echo "Long detailed description if needed"
 		}
-		
+
 		exit_help() {
 		    print_help
 		    exit 0
 		}
-		
+
 		exit_error() {
 		    print_help
 		    echo ""
 		    echo "ERROR: \$1"
 		    exit 1
 		}
-		
-		
+
+
 		POSITIONAL_ARGS=()
 		BOOL_OPT=1    # 1 = True
 		STR_OPT=""
-		
+
 		while [[ \$# -gt 0 ]]; do
 		    case \$1 in
 		        -h|--help)
@@ -221,24 +214,24 @@ then
 		            ;;
 		    esac
 		done
-		
+
 		set -- "\${POSITIONAL_ARGS[@]}"
-		
+
 		if [[ -z \${1+x} ]]
 		then
 		    exit_error "No [first argument] specified"
-		
+
 		elif [[ "\$1" != "possible-value-#1" ]] && [[ "\$1" != "possible-value-#2" ]]
 		then
 		    exit_error "Unknown [first argument] '\$1'. [First argument] must be one of the following: 'possible-value-#1', 'possible-value-#2'"
 		fi
-	
+
 		if [[ -n \${2+x} ]]
 		then
 		    echo "second argument is set!"
 		else
 		    echo "second argument is not set..."
-		fi	
+		fi 
 
 		FIRST_ARGUMENT="\$1"
 
@@ -250,10 +243,9 @@ then
 		fi
 		echo "STR_OPT: '\$STR_OPT'"
 		echo "\$FIRST_ARGUMENT"
-		EOF
+	EOF
 
-
-	[[ ! -f shell.nix ]] && cat <<- EOF > shell.nix
+	[[ ! -f shell.nix ]] && cat <<-EOF >shell.nix
 		with (import <nixpkgs> {});
 		mkShell {
 		    packages = [
@@ -263,34 +255,31 @@ then
 		                util-linux
 		            ];
 		            text = builtins.readFile ./source.sh;
-				})
+		        })
 		    ];
 		}
-		EOF
+	EOF
 
-    if [[ $GIT -eq 1 ]]
-    then
-        [[ ! -f .gitignore ]] && cat <<- EOF > .gitignore
+	if [[ $GIT -eq 1 ]]; then
+		[[ ! -f .gitignore ]] && cat <<-EOF >.gitignore
 			__pycache__/
 
 			.env*
 			!.env*.example
-			EOF
+		EOF
 
-
-		[[ ! -f README.md ]] && cat <<- EOF > README.md
+		[[ ! -f README.md ]] && cat <<-EOF >README.md
 			# $PROJECT_NAME
-			EOF
+		EOF
 
-        [[ ! -d .git ]] && { 
-            git init
-            if [[ $GGIT -eq 1 ]]
-            then
-                git add .
-                git commit -m "initial commit"
-            fi
-        }
-    fi
+		[[ ! -d .git ]] && {
+			git init
+			if [[ $GGIT -eq 1 ]]; then
+				git add .
+				git commit -m "initial commit"
+			fi
+		}
+	fi
 else
-    print_error "Unsupported type '$1'"
+	print_error "Unsupported type '$1'"
 fi
diff --git a/modules/wm/xmonad/scripts/set-brightness b/modules/wm/xmonad/scripts/set-brightness
--- a/modules/wm/xmonad/scripts/set-brightness
+++ b/modules/wm/xmonad/scripts/set-brightness
@@ -23,38 +23,34 @@ if [[ $STOP_EXECUTION_BEFORE_INTERPOLATION -eq 1 ]]; then
 	exit 1
 fi
 
-PRIMARY="<<primary-output-name>>"     # "eDP-1"
+PRIMARY="<<primary-output-name>>" # "eDP-1"
 
 CURR_VAL=$(xrandr --verbose | grep -oP "Brightness: \K.*")
-if [[ $CURR_VAL != "1.0" ]] && [[ $CURR_VAL != "0.75" ]] && [[ $CURR_VAL != "0.50" ]] && [[ $CURR_VAL != "0.25" ]]
-then
-    xrandr --output $PRIMARY --brightness 1
-    exit 0
+if [[ $CURR_VAL != "1.0" ]] && [[ $CURR_VAL != "0.75" ]] && [[ $CURR_VAL != "0.50" ]] && [[ $CURR_VAL != "0.25" ]]; then
+	xrandr --output "$PRIMARY" --brightness 1
+	exit 0
 fi
 
 re='^[+-]$'
 if ! [[ $1 =~ $re ]]; then
-	echo "error: first parameter must be either '+' or '-'" >&2; exit 1
+	echo "error: first parameter must be either '+' or '-'" >&2
+	exit 1
 fi
 
 if [[ $1 == '+' ]]; then
-    if [[ $CURR_VAL == "0.25" ]]
-    then
-        xrandr --output $PRIMARY --brightness 0.5
-    elif [[ $CURR_VAL == "0.50" ]]
-    then
-        xrandr --output $PRIMARY --brightness 0.75
-    else
-        xrandr --output $PRIMARY --brightness 1
-    fi
+	if [[ $CURR_VAL == "0.25" ]]; then
+		xrandr --output "$PRIMARY" --brightness 0.5
+	elif [[ $CURR_VAL == "0.50" ]]; then
+		xrandr --output "$PRIMARY" --brightness 0.75
+	else
+		xrandr --output "$PRIMARY" --brightness 1
+	fi
 else
-    if [[ $CURR_VAL == "1.0" ]]
-    then
-        xrandr --output $PRIMARY --brightness 0.75
-    elif [[ $CURR_VAL == "0.75" ]]
-    then
-        xrandr --output $PRIMARY --brightness 0.5
-    else
-        xrandr --output $PRIMARY --brightness 0.25
-    fi
+	if [[ $CURR_VAL == "1.0" ]]; then
+		xrandr --output "$PRIMARY" --brightness 0.75
+	elif [[ $CURR_VAL == "0.75" ]]; then
+		xrandr --output "$PRIMARY" --brightness 0.5
+	else
+		xrandr --output "$PRIMARY" --brightness 0.25
+	fi
 fi
